title: LKWSoul Wiki
description: lkwsoul.github.io
show_downloads: true
git_branch: master
logo_url: https://avatars2.githubusercontent.com/u/3321253?s=400&u=d72255673f4b8c01f92eb731621e184d9f8ff017&v=4
google_analytics:
theme: Git-Wiki
future: true
wiki_folder: _posts
use_github_wiki: false
use_prose_io: true
google_cse_token: 
custom_head: false
custom_sidebar: false
custom_footer: false
encoding: "utf-8"
gems:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-feed